export const ACTIONS = {
	USERS: {
		GET_ALL: 'USERS_GET_ALL',
		GET_USERS: 'USERS_GET_USERS',
		GET: 'USERS_GET',
		DELETE: 'DELETE_USER',
		SEARCH: 'SEARCH_USERS',
		PUT: 'PUT_USERS',
		POST: 'POST_USERS',
	},
	TOAST: {
		SUCCESS: 'SUCCESS_TOAST',
		ERROR: 'ERROR_TOAST',
	},
	ERROR: 'ERROR',
};
