export const COLLECTION_ACTIONS = {
	GETALL_SUCCESS: 'COLLECTION_GETALL_SUCCESS',
	GETALL_FAILURE: 'COLLECTION_GETALL_FAILURE',

	DESTROY: 'COLLECTION_DESTROY',

	GETONE_SUCCESS: 'COLLECTION_GETONE_SUCCESS',
	GETONE_FAILURE: 'COLLECTION_GETONE_FAILURE',

	ADD_SUCCESS: 'COLLECTION_ADD_SUCCESS',
	ADD_FAILURE: 'COLLECTION_ADD_FAILURE',

	DELETE_SUCCESS: 'COLLECTION_DELETE_SUCCESS',
	DELETE_FAILURE: 'COLLECTION_DELETE_FAILURE',

	MODIFY_SUCCESS: 'COLLECTION_MODIFY_SUCCESS',
	MODIFY_FAILURE: 'COLLECTION_MODIFY_FAILURE',
};
