export const COLLECTION_ACTIONS = {
	GET_ALL: 'COLLECTION_GET_ALL',
	GET_ONE: 'COLLECTION_GET_ONE',

	ADD_SUCCESS: 'COLLECTION_ADD_SUCCESS',
	ADD_FAILURE: 'COLLECTION_ADD_FAILURE',

	DELETE_SUCCESS: 'COLLECTION_DELETE_SUCCESS',
	DELETE_FAILURE: 'COLLECTION_DELETE_FAILURE',

	MODIFY_SUCCESS: 'COLLECTION_MODIFY_SUCCESS',
	MODIFY_FAILURE: 'COLLECTION_MODIFY_FAILURE',
};
